# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# INSTALL PLUGIN RELLOAD
unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "fedora/33-cloud-base"
  config.vm.box_version = "33.20201019.0"

  # VM fedora
  config.vm.define "fedora"  do |fedora|

    # VARIABLE HOSTNAME
    APP_NAME= "fedora-serv01"

    # HOSTNAME
    fedora.vm.hostname = APP_NAME

    # NETWORK
    fedora.vm.network "public_network" ,ip: "192.168.0.133",mode: "bridge",bridge: "ens32"


    # MOUNTS
    fedora.vm.synced_folder ".", "/vagrant", disabled: true
    fedora.vm.synced_folder "./security", "/security"

    # PROVIDER
    fedora.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name = APP_NAME
      vb.memory = 2048
      vb.cpus = 1
    end

    # PROVISION
    # SSH,FIREWALLD AND SELINUX
    fedora.vm.provision "shell", inline: <<-SHELL
      cat /security/id_rsa.pub >> .ssh/authorized_keys
    SHELL

    # # PACKAGES FOR PROVISION
    fedora.vm.provision "shell", inline: <<-SHELL
      # yum install python3 -y
      yum install  xorg-x11-server-Xorg xorg-x11-xauth xorg-x11-apps -y
    SHELL

  end

end
