# -*- mode: ruby -*-
# vi: set ft=ruby :

# INSTAL PLUGINS
unless Vagrant.has_plugin?("vagrant-reload")
  puts "Installing vagrant-reload Plugin..."
  system("vagrant plugin install vagrant-reload")
end
unless Vagrant.has_plugin?("vagrant-vbguest")
  puts "Installing vagrant-vbguest Plugin..."
  system("vagrant plugin install vagrant-vbguest")
end
unless Vagrant.has_plugin?("vagrant-disksize")
  puts "Installing vagrant-disksize Plugin..."
  system("vagrant plugin install vagrant-disksize")
end

# DEFINE MACHINE
Vagrant.configure("2") do |config|
  # SET BOX
  config.vm.box = "oraclelinux/9"
  config.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/9.json"
  config.vm.box_download_insecure = true

  # VBGuest Configs
  ## ISO path
  #config.vbguest.iso_path = "E:/VirtualBox_7.0.12/VBoxGuestAdditions_7.0.12.iso"
  ## do NOT download the iso file from a webserver
  #config.vbguest.no_remote = true

  # GLOBAL CUSTOMS
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../ansible", "/home/vagrant/ansible"
  config.vm.synced_folder "../../configs/linux/", "/home/vagrant/configs"
  config.vm.synced_folder "../../scripts/linux", "/home/vagrant/scripts"
  config.vm.synced_folder "../../security", "/home/vagrant/security"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "silvestrini-ol9"
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--vrde", "off"]  # Disable VRDE
  end

  # SETUP
  #config.vm.provision "shell", name: "[SCRIPT USERDATA-OL9.SH]", path: "../../scripts/linux/commons/userdata-ol9.sh"
  #Configure o provisionamento com Ansible
  config.vm.provision "ansible_local" do |ansible|
    ansible.install_mode = "pip3"
    ansible.compatibility_mode = "2.0"
    ansible.limit = "all"
    ansible.provisioning_path = "/home/vagrant/ansible"
    ansible.inventory_path = "hosts"
    ansible.playbook = "playbook.yaml"
  end
end
