# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Box Windows 10
  config.vm.box = "senglin/win-10-enterprise-vs2015community"
  config.vm.box_version = "1.0.0"
  config.vbguest.auto_update = true

  # VM CLIENT
  config.vm.define "srv01" do |srv01|

    # VARIABLE HOSTNAME
    VM_CLIENT_NAME= "srv01"

    # HOSTNAME
    srv01.vm.hostname = VM_CLIENT_NAME

    # NETWORK
    srv01.vm.network "public_network" ,ip: "192.168.0.143"

    # MOUNTS
    srv01.vm.synced_folder ".", "/vagrant", disabled: true
    srv01.vm.synced_folder "./scripts", "/scripts"

    # PROVIDER
    srv01.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name = VM_CLIENT_NAME
      vb.memory = 1024
      vb.cpus = 1
    end

    # PROVISION

    # SETUP CHOCOLATEY
    srv01.vm.provision "shell", path: "scripts/install_chocolatey.ps1"

    # SETUP ANSIBLE
    srv01.vm.provision "shell", path: "scripts/setup_ansible.ps1"

    # SETUP AD SERVER
    # srv01.vm.provision "ansible" do |ansible|
    #   ansible.limit = "all"
    #   ansible.inventory_path = "provisioning/hosts"
    #   ansible.playbook = "provisioning/client_server.yml"
    # end

  end

end