# -*- mode: ruby -*-
# vi: set ft=ruby :

# Require for create disks
require "fileutils"

# INSTALAÇÃO DE PLUGINS NECESSÁRIOS
required_plugins = ["vagrant-vmware-desktop", "vagrant-reload", "vagrant-vbguest", "vagrant-disksize"]
required_plugins.each do |plugin|
  unless Vagrant.has_plugin?(plugin)
    system "vagrant plugin install #{plugin}"
    puts "Installed the #{plugin} plugin."
  end
end

# VARIÁVEIS GLOBAIS
VM_NAME = "silvestrini-rocky9-dns"

# DEFINIÇÃO DA MÁQUINA VIRTUAL
Vagrant.configure("2") do |config|
  # CONFIGURAÇÃO DA BOX
  config.vm.box = "silvestrini-rocky9"
  config.vm.box_download_insecure = true

  # CONFIGURAÇÕES GLOBAIS
  config.ssh.insert_key = false

  # SHARED FOLDERS
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../ansible", "/home/vagrant/ansible"
  config.vm.synced_folder "../../configs/linux/", "/home/vagrant/configs"
  config.vm.synced_folder "../../scripts/linux", "/home/vagrant/scripts"
  config.vm.synced_folder "../../security", "/home/vagrant/security"

  # CONFIGURAÇÃO DO PROVEDOR VMWARE
  config.vm.provider "vmware_desktop" do |vm|
    vm.vmx["virtualHW.version"] = "10"
    vm.linked_clone = false
    vm.whitelist_verified = true
    vm.vmx["displayName"] = VM_NAME
    #vm.gui = true
  end
  # Configure dns
  config.vm.provision "shell", name: "[SCRIPT: scripts/linux/bind/userdata-bind-master.sh]", path: "../../scripts/linux/bind/userdata-bind-master.sh"
end
