debug: true
write-kubeconfig-mode: "0644"
tls-san:
  - rancher.skynet.com.br
  - 192.168.0.131
node-ip: ipNode
#node-external-ip: 192.168.0.131
bind-address: ipNode
advertise-address: ipNode
etcd-expose-metrics: true
cni:
  - canal
node-taint:
  - "CriticalAddonsOnly=true:NoExecute"